name: SPortal
author: solo
version: 0.0.1
api:
- 3.0.0-ALPHA11
main: solo\sportal\SPortal
softdepend:
- SWarp
permissions:
  sportal:
    default: op
    children:
      sportal.command:
        default: op
        children:
          sportal.command.create:
            default: op
          sportal.command.list:
            default: op
          sportal.command.remove:
            default: op
