name: SPortal
author: solo
version: 1.2.0
api: [3.0.0, 3.1.0, 4.0.0]
main: solo\sportal\SPortal
depend:
- SWarp
permissions:
  sportal:
    default: op
    children:
      sportal.command:
        default: op
        children:
          sportal.command.create:
            default: op
          sportal.command.list:
            default: op
          sportal.command.remove:
            default: op
